# Generated by Django 3.2.4 on 2022-03-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=100, unique=True)),
                ('mdesc', models.TextField(blank=True, null=True)),
                ('mimg', models.CharField(max_length=120)),
                ('mlink', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
    ]
